### ISSUE TITLE
Bugs-hideandseek

### ISSUE THREAD

**Issue by KayLemba** [Ewoskyx/portfolio_project#13]
1. The bug was a null exception at line 119. Checking for the null in an additional if statement did solve it. :)

const modalTitle = document.getElementById('modal-title');
  
  if (window.innerWidth < 992) {
    modalTitle.innerHTML = 'Multi-Post Stories';
  } else {
    modalTitle.innerHTML = `${title}`;
  }

2. The solution to this is as follows:
     function modalMobileTitle() {
  const modalTitle = document.getElementById("modal-title");
  if (modalTitle != null) {
    if (window.innerWidth < 992) {
      modalTitle.innerHTML = "Multi-Post Stories";
    } else {
      modalTitle.innerHTML = `${title}`;
    }
  }

**Comment by Ewoskyx** [comment]
Well done @KayLemba, you found it! :)
